import { Suspense } from "react";
import "./globals.css";
import Loading from "./loading";

export const metadata = {
  title: "Developer web - mobile - Christian",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Suspense fallback={<Loading />}>
        <body>{children}</body>
      </Suspense>
    </html>
  );
}
